@echo off
echo Starting Mine Subsidence Platform...
if not exist venv (
    echo Creating virtual environment...
    python -m venv venv
)
echo Starting Backend...
start cmd /k "call venv\Scripts\activate && pip install fastapi uvicorn paho-mqtt websockets && cd backend && python main.py"
echo Starting Simulator...
start cmd /k "call venv\Scripts\activate && python simulator\sensor_mesh.py"
echo Starting Frontend...
start cmd /k "cd frontend && npm install && npm run dev"
echo All services started! Close the command windows to stop the servers.

